"""Realtime event name constants."""

SEAT_LOCKED = "seat.locked"
SEAT_RELEASED = "seat.released"
SEAT_BOOKED = "seat.booked"
TICKET_VALIDATED = "ticket.validated"
TRIP_POSITION = "trip.position"
TRIP_ETA = "trip.eta"
TRIP_STATUS = "trip.status"
SOS_CREATED = "sos.created"
SOS_ACKNOWLEDGED = "sos.acknowledged"
LUGGAGE_SCANNED = "luggage.scanned"
SYNC_COMPLETED = "sync.completed"
BOOKING_UPDATED = "booking.updated"
AUDIT_EVENT = "audit.event"
OPERATIONS_UPDATED = "operations.updated"
